name: Latest blog post workflow
on: 
    schedule:
        - cron: '0 */6 * * *'
    workflow_dispatch:
permissions:
  contents: write
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v3
          - name: Pull in dev.to posts
            uses: gautamkrishnar/blog-post-workflow@v1
            with: 
              max_post_count: "5"
              feed_list: "https://dev.to/feed/tanvirrahman"
